INSERT INTO grade VALUES (1, 'Grado en Ingeniería Agrícola (Plan 2015)');
INSERT INTO grade VALUES (2, 'Grado en Ingeniería Eléctrica (Plan 2014)');
INSERT INTO grade VALUES (3, 'Grado en Ingeniería Electrónica Industrial (Plan 2010)');
INSERT INTO grade VALUES (4, 'Grado en Ingeniería Informática (Plan 2015)');
INSERT INTO grade VALUES (5, 'Grado en Ingeniería Mecánica (Plan 2010)');
INSERT INTO grade VALUES (6, 'Grado en Ingeniería Química Industrial (Plan 2010)');
INSERT INTO grade VALUES (7, 'Grado en Biotecnología (Plan 2015)');
INSERT INTO grade VALUES (8, 'Grado en Ciencias Ambientales (Plan 2009)');
INSERT INTO grade VALUES (9, 'Grado en Matemáticas (Plan 2010)');
INSERT INTO grade VALUES (10, 'Grado en Química (Plan 2009)');