-- llamada al procedimiento para cerar materias

CALL DATA_SUBJECT(1, 'Álgegra lineal y matemática discreta', 6, 'básica', 1, 1, 3, 4);
CALL DATA_SUBJECT(2, 'Cálculo', 6, 'básica', 1, 1, 14, 4);
CALL DATA_SUBJECT(3, 'Física para informática', 6, 'básica', 1, 1, 3, 4);
CALL DATA_SUBJECT(4, 'Introducción a la programación', 6, 'básica', 1, 1, 14, 4);
CALL DATA_SUBJECT(5, 'Organización y gestión de empresas', 6, 'básica', 1, 1, 3, 4);
CALL DATA_SUBJECT(6, 'Estadística', 6, 'básica', 1, 2, 14, 4);
CALL DATA_SUBJECT(7, 'Estructura y tecnología de computadores', 6, 'básica', 1, 2, 3, 4);
CALL DATA_SUBJECT(8, 'Fundamentos de electrónica', 6, 'básica', 1, 2, 14, 4);
CALL DATA_SUBJECT(9, 'Lógica y algorítmica', 6, 'básica', 1, 2, 3, 4);
CALL DATA_SUBJECT(10, 'Metodología de la programación', 6, 'básica', 1, 2, 14, 4);
CALL DATA_SUBJECT(11, 'Arquitectura de Computadores', 6, 'básica', 2, 1, 3, 4);
CALL DATA_SUBJECT(12, 'Estructura de Datos y Algoritmos I', 6, 'obligatoria', 2, 1, 3, 4);
CALL DATA_SUBJECT(13, 'Ingeniería del Software', 6, 'obligatoria', 2, 1, 14, 4);
CALL DATA_SUBJECT(14, 'Sistemas Inteligentes', 6, 'obligatoria', 2, 1, 3, 4);
CALL DATA_SUBJECT(15, 'Sistemas Operativos', 6, 'obligatoria', 2, 1, 14, 4);
CALL DATA_SUBJECT(16, 'Bases de Datos', 6, 'básica', 2, 2, 14, 4);
CALL DATA_SUBJECT(17, 'Estructura de Datos y Algoritmos II', 6, 'obligatoria', 2, 2, 14, 4);
CALL DATA_SUBJECT(18, 'Fundamentos de Redes de Computadores', 6 ,'obligatoria', 2, 2, 3, 4);
CALL DATA_SUBJECT(19, 'Planificación y Gestión de Proyectos Informáticos', 6, 'obligatoria', 2, 2, 3, 4);
CALL DATA_SUBJECT(20, 'Programación de Servicios Software', 6, 'obligatoria', 2, 2, 14, 4);
CALL DATA_SUBJECT(21, 'Desarrollo de interfaces de usuario', 6, 'obligatoria', 3, 1, 14, 4);
CALL DATA_SUBJECT(22, 'Ingeniería de Requisitos', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(23, 'Integración de las Tecnologías de la Información en las Organizaciones', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(24, 'Modelado y Diseño del Software 1', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(25, 'Multiprocesadores', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(26, 'Seguridad y cumplimiento normativo', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(27, 'Sistema de Información para las Organizaciones', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(28, 'Tecnologías web', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(29, 'Teoría de códigos y criptografía', 6, 'optativa', 3, 1, NULL, 4);
CALL DATA_SUBJECT(30, 'Administración de bases de datos', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(31, 'Herramientas y Métodos de Ingeniería del Software', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(32, 'Informática industrial y robótica', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(33, 'Ingeniería de Sistemas de Información', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(34, 'Modelado y Diseño del Software 2', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(35, 'Negocio Electrónico', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(36, 'Periféricos e interfaces', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(37, 'Sistemas de tiempo real', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(38, 'Tecnologías de acceso a red', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(39, 'Tratamiento digital de imágenes', 6, 'optativa', 3, 2, NULL, 4);
CALL DATA_SUBJECT(40, 'Administración de redes y sistemas operativos', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(41, 'Almacenes de Datos', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(42, 'Fiabilidad y Gestión de Riesgos', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(43, 'Líneas de Productos Software', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(44, 'Procesos de Ingeniería del Software 1', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(45, 'Tecnologías multimedia', 6, 'optativa', 4, 1, NULL, 4);
CALL DATA_SUBJECT(46, 'Análisis y planificación de las TI', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(47, 'Desarrollo Rápido de Aplicaciones', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(48, 'Gestión de la Calidad y de la Innovación Tecnológica', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(49, 'Inteligencia del Negocio', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(50, 'Procesos de Ingeniería del Software 2', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(51, 'Seguridad Informática', 6, 'optativa', 4, 2, NULL, 4);
CALL DATA_SUBJECT(52, 'Biologia celular', 6, 'básica', 1, 1, NULL, 7);
CALL DATA_SUBJECT(53, 'Física', 6, 'básica', 1, 1, NULL, 7);
CALL DATA_SUBJECT(54, 'Matemáticas I', 6, 'básica', 1, 1, NULL, 7);
CALL DATA_SUBJECT(55, 'Química general', 6, 'básica', 1, 1, NULL, 7);
CALL DATA_SUBJECT(56, 'Química orgánica', 6, 'básica', 1, 1, NULL, 7);
CALL DATA_SUBJECT(57, 'Biología vegetal y animal', 6, 'básica', 1, 2, NULL, 7);
CALL DATA_SUBJECT(58, 'Bioquímica', 6, 'básica', 1, 2, NULL, 7);
CALL DATA_SUBJECT(59, 'Genética', 6, 'básica', 1, 2, NULL, 7);
CALL DATA_SUBJECT(60, 'Matemáticas II', 6, 'básica', 1, 2, NULL, 7);
CALL DATA_SUBJECT(61, 'Microbiología', 6, 'básica', 1, 2, NULL, 7);
CALL DATA_SUBJECT(62, 'Botánica agrícola', 6, 'obligatoria', 2, 1, NULL, 7);
CALL DATA_SUBJECT(63, 'Fisiología vegetal', 6, 'obligatoria', 2, 1, NULL, 7);
CALL DATA_SUBJECT(64, 'Genética molecular', 6, 'obligatoria', 2, 1, NULL, 7);
CALL DATA_SUBJECT(65, 'Ingeniería bioquímica', 6, 'obligatoria', 2, 1, NULL, 7);
CALL DATA_SUBJECT(66, 'Termodinámica y cinética química aplicada', 6, 'obligatoria', 2, 1, NULL, 7);
CALL DATA_SUBJECT(67, 'Biorreactores', 6, 'obligatoria', 2, 2, NULL, 7);
CALL DATA_SUBJECT(68, 'Biotecnología microbiana', 6, 'obligatoria', 2, 2, NULL, 7);
CALL DATA_SUBJECT(69, 'Ingeniería genética', 6, 'obligatoria', 2, 2, NULL, 7);
CALL DATA_SUBJECT(70, 'Inmunología', 6, 'obligatoria', 2, 2, NULL, 7);
CALL DATA_SUBJECT(71, 'Virología', 6, 'obligatoria', 2, 2, NULL, 7);
CALL DATA_SUBJECT(72, 'Bases moleculares del desarrollo vegetal', 4.5, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(73, 'Fisiología animal', 4.5, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(74, 'Metabolismo y biosíntesis de biomoléculas', 6, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(75, 'Operaciones de separación', 6, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(76, 'Patología molecular de plantas', 4.5, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(77, 'Técnicas instrumentales básicas', 4.5, 'obligatoria', 3, 1, NULL, 7);
CALL DATA_SUBJECT(78, 'Bioinformática', 4.5, 'obligatoria', 3, 2, NULL, 7);
CALL DATA_SUBJECT(79, 'Biotecnología de los productos hortofrutículas', 4.5, 'obligatoria', 3, 2, NULL, 7);
CALL DATA_SUBJECT(80, 'Biotecnología vegetal', 6, 'obligatoria', 3, 2, NULL, 7);
CALL DATA_SUBJECT(81, 'Genómica y proteómica', 4.5, 'obligatoria', 3, 2, NULL, 7);
CALL DATA_SUBJECT(82, 'Procesos biotecnológicos', 6, 'obligatoria', 3, 2, NULL, 7);
CALL DATA_SUBJECT(83, 'Técnicas instrumentales avanzadas', 4.5, 'obligatoria', 3, 2, NULL, 7);